language: go
go:
- "1.15"

jobs:
  include:
  - stage: "GitHub Release"
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key: $GITHUB_API_TOKEN
      skip_cleanup: true
      on:
        tags: true