// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package handler

import (
	"esctl/internal/app"
	"esctl/internal/index/list"
	"esctl/internal/version"
	"esctl/pkg/es"
	"esctl/pkg/log"
	"github.com/google/wire"
)

// Injectors from registry.go:

func NewRegistry(a app.IApp, logHelper log.IHelper, esHelper es.IHelper) *Registry {
	iHandler := version.NewHandler(a)
	listIHandler := list.NewHandler(a)
	registry := &Registry{
		Version:   iHandler,
		IndexList: listIHandler,
	}
	return registry
}

// registry.go:

type Registry struct {
	Version   version.IHandler
	IndexList list.IHandler
}

var providerSet = wire.NewSet(version.NewHandler, list.NewHandler)
